function keys
  echo "COMMAND                   |  DEFAULT KEY SEQUENCE"
  echo "-- FZF ---------------------------------------------------------------"
  echo "Search and insert file    |  Ctrl-T"
  echo "Cd into directory         |  Alt-C"
  echo "Kill process              |  Ctrl-P"
  echo "Jump to mark              |  Ctrl-E          (E for explore)"
  echo ""
  echo "-- GIT (Ctrl-G) + ---------- Note: Ctrl is optional ------------------"
  echo "Files                     |  Ctrl-F          (F for files)"
  echo "Branches                  |  Ctrl-B          (B for branches)"
  echo "Tags                      |  Ctrl-T          (T for tags)"
  echo "Remotes                   |  Ctrl-R          (R for remotes)"
  echo "Commit Hashes             |  Ctrl-H          (H for hashes)"
  echo "Stashes                   |  Ctrl-S          (S for stashes)"
  echo "Reflogs                   |  Ctrl-L          (L for reflogs)"
  echo "Worktrees                 |  Ctrl-W          (W for worktrees)"
  echo "Each ref                  |  Ctrl-E          (E for each ref)"
  echo ""
  echo "Inside fzf"
  echo "    TAB or SHIFT-TAB to select multiple objects"
  echo "    CTRL-/ to change preview window layout"
  echo "    CTRL-O to open the object in the web browser (in GitHub URL scheme)"
  echo ""
  echo "-- FZF (PatrickF1) -- mostly unbinded? -------------------------------"
  echo "Search Directory          |  Ctrl+Alt+F      (F for file)"
  echo "Search History            |  Ctrl+R          (R for reverse)"
  echo "Search Processes          |  Ctrl+Alt+P      (P for process)"
  echo "Search Variables          |  Ctrl+V          (V for variable)"
  echo "Jump to mark              |  Ctrl-G          (G for goto)"
  echo ""
  echo "-- Tmux (Requires Ctrl-a unless otherwise specified) -----------------"
  echo "Split window horizontally |  \" / h           (h for horizontal)"
  echo "Split window vertically   |  % / v           (v for vertical)"
  echo "Maximize current panel    |  z               (z for zoom)"
  echo "Reload .tmux.conf         |  R               (R for reload)"
  echo "Send to all panes on      |  e               (e for echo)"
  echo "Send to all panes off     |  E               (E for echo)"
  echo "Kill session              |  K               (K for kill)"
  echo "Chat with LLM             |  i               (i for intelligence)"
  echo "Next window               |  n / Alt-PgDown  (n for next)"
  echo "Previous window           |  p / Alt-PgUp    (p for previous)"
  echo "Clear terminal and buffer |  l               (l is standard in shell)"
  echo "Scroll up                 |  Shift-PgUp"
  echo "Scroll down               |  Shift-PgDown"
  echo "Previous window           |  Ctrl-a twice"
  echo "Send Ctrl-a when nested   |  Send-q"
  echo "Install tmux plugins      |  I               (I for install)"
  echo "Uninstall plugins         |  alt-u           (u for uninstall)"
end
