function keys
  echo "COMMAND                   |  DEFAULT KEY SEQUENCE"
  echo "-- FZF ---------------------------------------------------------------"
  echo "Search Directory          |  Ctrl+Alt+F (F for file)"
  echo "Search Git Log            |  Ctrl+Alt+L (L for log)"
  echo "Search Git Status         |  Ctrl+Alt+S (S for status)"
  echo "Search History            |  Ctrl+R     (R for reverse)"
  echo "Search Processes          |  Ctrl+Alt+P (P for process)"
  echo "Search Variables          |  Ctrl+V     (V for variable)"
  echo "Jump to mark              |  Ctrl-G     (G for goto)"
  echo "-- Tmux (Requires Ctrl-a unless otherwise specified) -----------------"
  echo "Split window horizontally |  \""
  echo "Split window vertically   |  %"
  echo "Maximize current panel    |  z               (z for zoom)"
  echo "Reload .tmux.conf         |  R               (R for reload)"
  echo "Send to all panes on      |  e               (e for echo)"
  echo "Send to all panes off     |  E               (E for echo)"
  echo "Kill session              |  K               (K for kill)"
  echo "Chat with llm             |  i               (i for intelligence)"
  echo "Next window               |  n / Alt-PgDown  (n for next)"
  echo "Previous window           |  p / Alt-PgUp    (p for previous)"
  echo "Scroll up                 |  Shift-PgUp"
  echo "Scroll down               |  Shift-PgDown"
  echo "Previous window           |  Ctrl-a twice"
  echo "Send Ctrl-a when nested   |  Send-q"
end
